# Generated by Django 3.1.1 on 2020-09-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='other_text',
            new_name='other_details',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='website_text',
            new_name='website_name',
        ),
    ]
