# Generated by Django 3.1.1 on 2020-09-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_auto_20200924_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='other_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
