# Generated by Django 3.1.1 on 2020-09-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_auto_20200926_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='website',
            new_name='website_id',
        ),
    ]
