# Generated by Django 3.1.1 on 2020-09-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_auto_20200928_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='max_length',
            new_name='max_len',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='min_length',
            new_name='min_len',
        ),
    ]
